sudo: false

language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - TEST_ELASTICSEARCH=1 TEST_LIVE=1 TEST_HOST=localhost TEST_PORT=9200 TEST_COUCHDB=http://localhost:5984/

services:
  - elasticsearch
  - couchdb

before_install:
  - sleep $(( $RANDOM % 60 ))
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm --notest --verbose App::ModuleBuildTiny Devel::Cover Devel::Cover::Report::Coveralls
  - mbtiny listdeps | cpanm --notest --verbose

script:
  PERL5OPT=-MDevel::Cover prove -l -v -r t && cover -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

git:
  depth: 1
