sudo: required

language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - TEST_ELASTICSEARCH=1 TEST_LIVE=1 TEST_HOST=localhost TEST_PORT=9200 TEST_COUCHDB=http://localhost:5984/

services:
  - elasticsearch
  - couchdb

before_install:
  - sleep 10
  - yes | perl -MCPAN::FirstTime -e CPAN::FirstTime::init
  - cpanm --notest --verbose Module::Install Module::Install::CPANfile Devel::Cover Devel::Cover::Report::Coveralls

script:
  PERL5OPT=-MDevel::Cover prove -Ilib -v -r t && cover -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

git:
  depth: 1
